# Generated by Django 2.0.6 on 2018-07-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutritional_database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NDB_NO', models.BigIntegerField()),
                ('Measure', models.CharField(default='', max_length=20)),
                ('Weight_g', models.DecimalField(decimal_places=4, default=-1, max_digits=20)),
                ('Description', models.CharField(default='', max_length=200)),
                ('Category', models.CharField(default=-1, max_length=200)),
                ('Energy_kcal', models.CharField(default='', max_length=20)),
                ('Total_lipid_fat_g', models.CharField(default='', max_length=20)),
                ('Carbohydrate_by_diff_g', models.CharField(default='', max_length=20)),
                ('Fiber_total_dietary_g', models.CharField(default='', max_length=20)),
                ('Cholesterol_mg', models.CharField(default='', max_length=20)),
                ('Fatty_acids_saturated_g', models.CharField(default='', max_length=20)),
                ('Fatty_acids_total_monounsaturated_g', models.CharField(default='', max_length=20)),
                ('Fatty_acids_total_polyunsaturated_g', models.CharField(default='', max_length=20)),
                ('Fatty_acids_total_trans_g', models.CharField(default='', max_length=20)),
                ('Iron_mg', models.CharField(default='', max_length=20)),
                ('Magnesium_mg', models.CharField(default='', max_length=20)),
                ('Magnesium_mng', models.CharField(default='', max_length=20)),
                ('Thiamin_mg', models.CharField(default='', max_length=20)),
                ('Vitamin_D_microg', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Substitution_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Substitution', models.CharField(max_length=500)),
                ('Ingredient', models.CharField(max_length=500)),
            ],
        ),
    ]
